# config.py

# IDs de Cuentas y Conceptos
IDS_INGRESOS = [58, 384]     
ID_COSTO_RETAIL = 76         
ID_COSTO_INSTALACION = 399   
ID_SUMINISTROS_PROY = 400    
ID_WIP = 503                 
ID_PROVISION_PROY = 504      
ID_AJUSTES_INV = 395         

TODOS_LOS_IDS = IDS_INGRESOS + [ID_WIP, ID_PROVISION_PROY, ID_COSTO_INSTALACION, ID_SUMINISTROS_PROY, ID_AJUSTES_INV, ID_COSTO_RETAIL]
